import type { CommonAllergen, NutritionFacts } from "./balancedMeals";

/**
 * Versioned, source-linked foods that remain available to every CUT OS user.
 * Values come from the USDA FoodData Central records already frozen in
 * NUTRITION_CATALOG_EVIDENCE.md. Packaged-food barcode results and user-created
 * foods are separate catalogs because their source and confidence differ.
 */
export const CURATED_FOOD_CATALOG_VERSION = "2026-09-04.2";

export interface CuratedFoodItem {
  id: string;
  name: string;
  aliases: readonly string[];
  servingDescription: string;
  servingGrams: number;
  cuisineTags: readonly string[];
  dietaryTags: readonly CuratedFoodDietaryTag[];
  commonAllergens: readonly CommonAllergen[];
  nutritionPerServing: NutritionFacts;
  source: "USDA FoodData Central";
  sourceId: number;
}

export type CuratedFoodDietaryTag = "vegetarian" | "vegan" | "pescatarian";

interface CuratedFoodSeed {
  id: string;
  name: string;
  aliases?: readonly string[];
  servingGrams: number;
  cuisineTags?: readonly string[];
  commonAllergens?: readonly CommonAllergen[];
  sourceId: number;
  per100g: NutritionFacts;
}

function round(value: number, places: number): number {
  const factor = 10 ** places;
  return Math.round((value + Number.EPSILON) * factor) / factor;
}

export function nutritionForGrams(
  nutrition: NutritionFacts,
  grams: number,
): NutritionFacts {
  const factor = grams / 100;
  return {
    caloriesKcal: round(nutrition.caloriesKcal * factor, 0),
    proteinG: round(nutrition.proteinG * factor, 1),
    carbsG: round(nutrition.carbsG * factor, 1),
    fatG: round(nutrition.fatG * factor, 1),
    fiberG: round(nutrition.fiberG * factor, 1),
  };
}

const NON_VEGAN_FOOD_DIETARY_TAGS: Readonly<
  Record<string, readonly CuratedFoodDietaryTag[]>
> = Object.freeze({
  "chicken-breast-roasted": [],
  "chicken-breast-stewed": [],
  "egg-hard-boiled": ["vegetarian"],
  "greek-yogurt-nonfat": ["vegetarian"],
  "salmon-cooked": ["pescatarian"],
  "chicken-thigh-roasted": [],
  "beef-top-round-roasted": [],
  "goat-roasted": [],
  "turkey-breast-roasted": [],
  "tilapia-cooked": ["pescatarian"],
  "carp-cooked": ["pescatarian"],
  "cod-cooked": ["pescatarian"],
  "shrimp-cooked": ["pescatarian"],
  "tuna-canned-water": ["pescatarian"],
  "sardines-canned-oil": ["pescatarian"],
  "milk-two-percent": ["vegetarian"],
  "yogurt-plain-lowfat": ["vegetarian"],
  "cottage-cheese-lowfat": ["vegetarian"],
  paneer: ["vegetarian"],
  naan: ["vegetarian"],
  paratha: ["vegetarian"],
  "butter-salted": ["vegetarian"],
});

function dietaryTagsForFood(id: string): readonly CuratedFoodDietaryTag[] {
  return NON_VEGAN_FOOD_DIETARY_TAGS[id] ?? ["vegan"];
}

const SEEDS: readonly CuratedFoodSeed[] = [
  {
    id: "chicken-breast-roasted",
    name: "Chicken breast, roasted",
    aliases: ["murgi", "chicken"],
    servingGrams: 150,
    cuisineTags: ["desi"],
    sourceId: 171477,
    per100g: {
      caloriesKcal: 165,
      proteinG: 31.02,
      carbsG: 0,
      fatG: 3.57,
      fiberG: 0,
    },
  },
  {
    id: "chicken-breast-stewed",
    name: "Chicken breast, stewed",
    aliases: ["chicken curry", "murgir mangsho"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 171478,
    per100g: {
      caloriesKcal: 151,
      proteinG: 28.98,
      carbsG: 0,
      fatG: 3.03,
      fiberG: 0,
    },
  },
  {
    id: "lentils-cooked",
    name: "Lentils, cooked",
    aliases: ["dal", "daal", "masoor dal", "mosur dal"],
    servingGrams: 180,
    cuisineTags: ["bengali", "desi"],
    sourceId: 172421,
    per100g: {
      caloriesKcal: 116,
      proteinG: 9.02,
      carbsG: 20.13,
      fatG: 0.38,
      fiberG: 7.9,
    },
  },
  {
    id: "rice-white-cooked",
    name: "White rice, cooked",
    aliases: ["bhaat", "basmati rice", "chawal"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168878,
    per100g: {
      caloriesKcal: 130,
      proteinG: 2.69,
      carbsG: 28.17,
      fatG: 0.28,
      fiberG: 0.4,
    },
  },
  {
    id: "rice-brown-cooked",
    name: "Brown rice, cooked",
    aliases: ["brown basmati", "chawal"],
    servingGrams: 150,
    cuisineTags: ["desi"],
    sourceId: 169704,
    per100g: {
      caloriesKcal: 123,
      proteinG: 2.74,
      carbsG: 25.58,
      fatG: 0.97,
      fiberG: 1.6,
    },
  },
  {
    id: "egg-hard-boiled",
    name: "Egg, hard-boiled",
    aliases: ["dim", "anda", "boiled egg"],
    servingGrams: 100,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["egg"],
    sourceId: 173424,
    per100g: {
      caloriesKcal: 155,
      proteinG: 12.58,
      carbsG: 1.12,
      fatG: 10.61,
      fiberG: 0,
    },
  },
  {
    id: "salmon-cooked",
    name: "Atlantic salmon, cooked",
    aliases: ["salmon fish", "mach"],
    servingGrams: 150,
    commonAllergens: ["fish"],
    sourceId: 175168,
    per100g: {
      caloriesKcal: 206,
      proteinG: 22.1,
      carbsG: 0,
      fatG: 12.35,
      fiberG: 0,
    },
  },
  {
    id: "tofu-firm",
    name: "Firm tofu",
    aliases: ["bean curd"],
    servingGrams: 150,
    commonAllergens: ["soy"],
    sourceId: 172475,
    per100g: {
      caloriesKcal: 144,
      proteinG: 17.27,
      carbsG: 2.78,
      fatG: 8.72,
      fiberG: 2.3,
    },
  },
  {
    id: "edamame-prepared",
    name: "Edamame, prepared",
    aliases: ["soy beans"],
    servingGrams: 100,
    commonAllergens: ["soy"],
    sourceId: 168411,
    per100g: {
      caloriesKcal: 121,
      proteinG: 11.91,
      carbsG: 8.91,
      fatG: 5.2,
      fiberG: 5.2,
    },
  },
  {
    id: "greek-yogurt-nonfat",
    name: "Plain nonfat Greek yogurt",
    aliases: ["yogurt", "dahi-style yogurt"],
    servingGrams: 200,
    cuisineTags: ["desi"],
    commonAllergens: ["milk"],
    sourceId: 170894,
    per100g: {
      caloriesKcal: 59,
      proteinG: 10.19,
      carbsG: 3.6,
      fatG: 0.39,
      fiberG: 0,
    },
  },
  {
    id: "oats-dry",
    name: "Rolled oats, dry",
    aliases: ["oatmeal"],
    servingGrams: 40,
    sourceId: 173904,
    per100g: {
      caloriesKcal: 379,
      proteinG: 13.15,
      carbsG: 67.7,
      fatG: 6.52,
      fiberG: 10.1,
    },
  },
  {
    id: "quinoa-cooked",
    name: "Quinoa, cooked",
    aliases: ["quinoa grain"],
    servingGrams: 150,
    sourceId: 168917,
    per100g: {
      caloriesKcal: 120,
      proteinG: 4.4,
      carbsG: 21.3,
      fatG: 1.92,
      fiberG: 2.8,
    },
  },
  {
    id: "sweet-potato-baked",
    name: "Sweet potato, baked",
    aliases: ["mishti alu", "shakarkandi"],
    servingGrams: 200,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168483,
    per100g: {
      caloriesKcal: 90,
      proteinG: 2.01,
      carbsG: 20.71,
      fatG: 0.15,
      fiberG: 3.3,
    },
  },
  {
    id: "spinach-cooked",
    name: "Spinach, cooked",
    aliases: ["palong shaak", "palak", "saag"],
    servingGrams: 100,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168463,
    per100g: {
      caloriesKcal: 23,
      proteinG: 2.97,
      carbsG: 3.75,
      fatG: 0.26,
      fiberG: 2.4,
    },
  },
  {
    id: "broccoli-cooked",
    name: "Broccoli, cooked",
    aliases: ["broccoli florets"],
    servingGrams: 100,
    sourceId: 169967,
    per100g: {
      caloriesKcal: 35,
      proteinG: 2.38,
      carbsG: 7.18,
      fatG: 0.41,
      fiberG: 3.3,
    },
  },
  {
    id: "zucchini-cooked",
    name: "Zucchini, cooked",
    aliases: ["summer squash"],
    servingGrams: 100,
    sourceId: 169292,
    per100g: {
      caloriesKcal: 15,
      proteinG: 1.14,
      carbsG: 2.69,
      fatG: 0.36,
      fiberG: 1,
    },
  },
  {
    id: "cucumber-raw",
    name: "Cucumber, raw",
    aliases: ["shosha", "kheera", "cucumber salad"],
    servingGrams: 100,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168409,
    per100g: {
      caloriesKcal: 15,
      proteinG: 0.65,
      carbsG: 3.63,
      fatG: 0.11,
      fiberG: 0.5,
    },
  },
  {
    id: "tomato-raw",
    name: "Tomato, raw",
    aliases: ["tomato salad", "tamatar"],
    servingGrams: 100,
    cuisineTags: ["desi"],
    sourceId: 170457,
    per100g: {
      caloriesKcal: 18,
      proteinG: 0.88,
      carbsG: 3.89,
      fatG: 0.2,
      fiberG: 1.2,
    },
  },
  {
    id: "onion-raw",
    name: "Onion, raw",
    aliases: ["peyaj", "pyaaz"],
    servingGrams: 100,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170000,
    per100g: {
      caloriesKcal: 40,
      proteinG: 1.1,
      carbsG: 9.34,
      fatG: 0.1,
      fiberG: 1.7,
    },
  },
  {
    id: "red-pepper-raw",
    name: "Red bell pepper, raw",
    aliases: ["capsicum", "sweet pepper"],
    servingGrams: 100,
    sourceId: 170108,
    per100g: {
      caloriesKcal: 26,
      proteinG: 0.99,
      carbsG: 6.03,
      fatG: 0.3,
      fiberG: 2.1,
    },
  },
  {
    id: "red-cabbage-raw",
    name: "Red cabbage, raw",
    aliases: ["cabbage salad"],
    servingGrams: 100,
    sourceId: 169977,
    per100g: {
      caloriesKcal: 31,
      proteinG: 1.43,
      carbsG: 7.37,
      fatG: 0.16,
      fiberG: 2.1,
    },
  },
  {
    id: "romaine-raw",
    name: "Romaine lettuce, raw",
    aliases: ["lettuce", "salad greens"],
    servingGrams: 100,
    sourceId: 169247,
    per100g: {
      caloriesKcal: 17,
      proteinG: 1.23,
      carbsG: 3.29,
      fatG: 0.3,
      fiberG: 2.1,
    },
  },
  {
    id: "strawberries-raw",
    name: "Strawberries, raw",
    aliases: ["strawberry"],
    servingGrams: 100,
    sourceId: 167762,
    per100g: {
      caloriesKcal: 32,
      proteinG: 0.67,
      carbsG: 7.68,
      fatG: 0.3,
      fiberG: 2,
    },
  },
  {
    id: "blueberries-raw",
    name: "Blueberries, raw",
    aliases: ["blueberry"],
    servingGrams: 100,
    sourceId: 171711,
    per100g: {
      caloriesKcal: 57,
      proteinG: 0.74,
      carbsG: 14.49,
      fatG: 0.33,
      fiberG: 2.4,
    },
  },
  {
    id: "banana-raw",
    name: "Banana, raw",
    aliases: ["kola", "banana fruit"],
    servingGrams: 100,
    cuisineTags: ["bengali", "desi"],
    sourceId: 173944,
    per100g: {
      caloriesKcal: 89,
      proteinG: 1.09,
      carbsG: 22.84,
      fatG: 0.33,
      fiberG: 2.6,
    },
  },
  {
    id: "chia-seeds",
    name: "Chia seeds",
    aliases: ["chia"],
    servingGrams: 10,
    sourceId: 170554,
    per100g: {
      caloriesKcal: 486,
      proteinG: 16.54,
      carbsG: 42.12,
      fatG: 30.74,
      fiberG: 34.4,
    },
  },
  {
    id: "sesame-seeds",
    name: "Sesame seeds",
    aliases: ["til", "sesame"],
    servingGrams: 10,
    cuisineTags: ["desi"],
    commonAllergens: ["sesame"],
    sourceId: 170150,
    per100g: {
      caloriesKcal: 573,
      proteinG: 17.73,
      carbsG: 23.45,
      fatG: 49.67,
      fiberG: 11.8,
    },
  },
  {
    id: "olive-oil",
    name: "Olive oil",
    aliases: ["cooking oil"],
    servingGrams: 5,
    sourceId: 171413,
    per100g: {
      caloriesKcal: 884,
      proteinG: 0,
      carbsG: 0,
      fatG: 100,
      fiberG: 0,
    },
  },
  {
    id: "sesame-oil",
    name: "Sesame oil",
    aliases: ["til oil"],
    servingGrams: 5,
    commonAllergens: ["sesame"],
    sourceId: 171016,
    per100g: {
      caloriesKcal: 884,
      proteinG: 0,
      carbsG: 0,
      fatG: 100,
      fiberG: 0,
    },
  },
  {
    id: "lemon-juice",
    name: "Lemon juice",
    aliases: ["lebu", "nimbu juice"],
    servingGrams: 30,
    cuisineTags: ["bengali", "desi"],
    sourceId: 167747,
    per100g: {
      caloriesKcal: 22,
      proteinG: 0.35,
      carbsG: 6.9,
      fatG: 0.24,
      fiberG: 0.3,
    },
  },
  {
    id: "garlic-raw",
    name: "Garlic, raw",
    aliases: ["roshun", "lahsun"],
    servingGrams: 5,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169230,
    per100g: {
      caloriesKcal: 149,
      proteinG: 6.36,
      carbsG: 33.06,
      fatG: 0.5,
      fiberG: 2.1,
    },
  },
  {
    id: "ginger-raw",
    name: "Ginger, raw",
    aliases: ["ada", "adrak"],
    servingGrams: 5,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169231,
    per100g: {
      caloriesKcal: 80,
      proteinG: 1.82,
      carbsG: 17.77,
      fatG: 0.75,
      fiberG: 2,
    },
  },
  {
    id: "parsley-fresh",
    name: "Parsley, fresh",
    aliases: ["parsley herb"],
    servingGrams: 10,
    sourceId: 170416,
    per100g: {
      caloriesKcal: 36,
      proteinG: 2.97,
      carbsG: 6.33,
      fatG: 0.79,
      fiberG: 3.3,
    },
  },
  {
    id: "cumin-ground",
    name: "Cumin, ground",
    aliases: ["jeera", "jira"],
    servingGrams: 1,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170923,
    per100g: {
      caloriesKcal: 375,
      proteinG: 17.81,
      carbsG: 44.24,
      fatG: 22.27,
      fiberG: 10.5,
    },
  },
  {
    id: "turmeric-ground",
    name: "Turmeric, ground",
    aliases: ["holud", "haldi"],
    servingGrams: 1,
    cuisineTags: ["bengali", "desi"],
    sourceId: 172231,
    per100g: {
      caloriesKcal: 312,
      proteinG: 9.68,
      carbsG: 67.14,
      fatG: 3.25,
      fiberG: 22.7,
    },
  },
  {
    id: "chicken-thigh-roasted",
    name: "Chicken thigh, roasted",
    aliases: ["murgir raan", "dark meat chicken", "chicken curry piece"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 172388,
    per100g: {
      caloriesKcal: 179,
      proteinG: 24.76,
      carbsG: 0,
      fatG: 8.15,
      fiberG: 0,
    },
  },
  {
    id: "beef-top-round-roasted",
    name: "Lean beef top round, roasted",
    aliases: ["gorur mangsho", "beef bhuna", "lean beef curry"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 171771,
    per100g: {
      caloriesKcal: 150,
      proteinG: 29.81,
      carbsG: 0,
      fatG: 3.37,
      fiberG: 0,
    },
  },
  {
    id: "goat-roasted",
    name: "Goat, roasted",
    aliases: ["khashi", "chagol", "goat curry", "mutton-style goat"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 175304,
    per100g: {
      caloriesKcal: 143,
      proteinG: 27.1,
      carbsG: 0,
      fatG: 3.03,
      fiberG: 0,
    },
  },
  {
    id: "turkey-breast-roasted",
    name: "Turkey breast, roasted",
    aliases: ["turkey", "lean turkey", "turkey curry"],
    servingGrams: 150,
    cuisineTags: ["north-american-desi"],
    sourceId: 171496,
    per100g: {
      caloriesKcal: 147,
      proteinG: 30.13,
      carbsG: 0,
      fatG: 2.08,
      fiberG: 0,
    },
  },
  {
    id: "tilapia-cooked",
    name: "Tilapia, cooked",
    aliases: ["tilapia mach", "fish curry", "machher jhol"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["fish"],
    sourceId: 175177,
    per100g: {
      caloriesKcal: 128,
      proteinG: 26.15,
      carbsG: 0,
      fatG: 2.65,
      fiberG: 0,
    },
  },
  {
    id: "carp-cooked",
    name: "Carp, cooked",
    aliases: ["rui-style fish", "rohu-style fish", "carp mach", "machher jhol"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["fish"],
    sourceId: 174185,
    per100g: {
      caloriesKcal: 162,
      proteinG: 22.86,
      carbsG: 0,
      fatG: 7.17,
      fiberG: 0,
    },
  },
  {
    id: "cod-cooked",
    name: "Pacific cod, cooked",
    aliases: ["cod fish", "white fish", "fish curry"],
    servingGrams: 150,
    cuisineTags: ["north-american-desi"],
    commonAllergens: ["fish"],
    sourceId: 171990,
    per100g: {
      caloriesKcal: 85,
      proteinG: 18.73,
      carbsG: 0,
      fatG: 0.5,
      fiberG: 0,
    },
  },
  {
    id: "shrimp-cooked",
    name: "Shrimp, cooked",
    aliases: ["chingri", "prawn", "shrimp curry"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["shellfish"],
    sourceId: 171971,
    per100g: {
      caloriesKcal: 119,
      proteinG: 22.78,
      carbsG: 1.52,
      fatG: 1.7,
      fiberG: 0,
    },
  },
  {
    id: "tuna-canned-water",
    name: "Light tuna, canned in water",
    aliases: ["canned tuna", "tuna bhorta", "tuna mash"],
    servingGrams: 120,
    cuisineTags: ["north-american-desi"],
    commonAllergens: ["fish"],
    sourceId: 171986,
    per100g: {
      caloriesKcal: 116,
      proteinG: 25.51,
      carbsG: 0,
      fatG: 0.82,
      fiberG: 0,
    },
  },
  {
    id: "sardines-canned-oil",
    name: "Sardines, canned in oil",
    aliases: ["sardine fish", "canned fish", "sardine bhorta"],
    servingGrams: 100,
    cuisineTags: ["north-american-desi"],
    commonAllergens: ["fish"],
    sourceId: 175139,
    per100g: {
      caloriesKcal: 208,
      proteinG: 24.62,
      carbsG: 0,
      fatG: 11.45,
      fiberG: 0,
    },
  },
  {
    id: "chickpeas-cooked",
    name: "Chickpeas, cooked",
    aliases: ["chola", "chana", "garbanzo", "bengal gram", "chana masala"],
    servingGrams: 180,
    cuisineTags: ["bengali", "desi"],
    sourceId: 173757,
    per100g: {
      caloriesKcal: 164,
      proteinG: 8.86,
      carbsG: 27.42,
      fatG: 2.59,
      fiberG: 7.6,
    },
  },
  {
    id: "kidney-beans-cooked",
    name: "Red kidney beans, cooked",
    aliases: ["rajma", "kidney bean curry"],
    servingGrams: 180,
    cuisineTags: ["desi"],
    sourceId: 175194,
    per100g: {
      caloriesKcal: 127,
      proteinG: 8.67,
      carbsG: 22.8,
      fatG: 0.5,
      fiberG: 7.4,
    },
  },
  {
    id: "mung-beans-cooked",
    name: "Mung beans, cooked",
    aliases: ["moong dal", "mung dal", "mug dal"],
    servingGrams: 180,
    cuisineTags: ["bengali", "desi"],
    sourceId: 174257,
    per100g: {
      caloriesKcal: 105,
      proteinG: 7.02,
      carbsG: 19.15,
      fatG: 0.38,
      fiberG: 7.6,
    },
  },
  {
    id: "split-peas-cooked",
    name: "Split peas, cooked",
    aliases: ["motor dal", "matar dal", "split pea dal"],
    servingGrams: 180,
    cuisineTags: ["bengali", "desi"],
    sourceId: 172429,
    per100g: {
      caloriesKcal: 118,
      proteinG: 8.34,
      carbsG: 21.1,
      fatG: 0.39,
      fiberG: 8.3,
    },
  },
  {
    id: "black-beans-cooked",
    name: "Black beans, cooked",
    aliases: ["black bean", "kalo bean"],
    servingGrams: 180,
    cuisineTags: ["north-american-desi"],
    sourceId: 173735,
    per100g: {
      caloriesKcal: 132,
      proteinG: 8.86,
      carbsG: 23.71,
      fatG: 0.54,
      fiberG: 8.7,
    },
  },
  {
    id: "milk-two-percent",
    name: "Milk, 2%",
    aliases: ["dudh", "doodh", "reduced-fat milk"],
    servingGrams: 244,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["milk"],
    sourceId: 172205,
    per100g: {
      caloriesKcal: 50,
      proteinG: 3.3,
      carbsG: 4.8,
      fatG: 1.98,
      fiberG: 0,
    },
  },
  {
    id: "yogurt-plain-lowfat",
    name: "Plain low-fat yogurt",
    aliases: ["doi", "dahi", "raita yogurt"],
    servingGrams: 180,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["milk"],
    sourceId: 170886,
    per100g: {
      caloriesKcal: 63,
      proteinG: 5.25,
      carbsG: 7.04,
      fatG: 1.55,
      fiberG: 0,
    },
  },
  {
    id: "cottage-cheese-lowfat",
    name: "Low-fat cottage cheese",
    aliases: ["cottage cheese", "high-protein cheese"],
    servingGrams: 150,
    commonAllergens: ["milk"],
    sourceId: 172182,
    per100g: {
      caloriesKcal: 81,
      proteinG: 10.45,
      carbsG: 4.76,
      fatG: 2.27,
      fiberG: 0,
    },
  },
  {
    id: "paneer",
    name: "Paneer",
    aliases: ["panir", "Indian cottage cheese"],
    servingGrams: 100,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["milk"],
    sourceId: 2705740,
    per100g: {
      caloriesKcal: 299,
      proteinG: 15.9,
      carbsG: 22.5,
      fatG: 15.5,
      fiberG: 0,
    },
  },
  {
    id: "roti",
    name: "Chapati or roti",
    aliases: ["ruti", "atta roti", "whole-wheat flatbread"],
    servingGrams: 40,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["wheat"],
    sourceId: 2707713,
    per100g: {
      caloriesKcal: 299,
      proteinG: 7.85,
      carbsG: 46.1,
      fatG: 9.2,
      fiberG: 9.7,
    },
  },
  {
    id: "naan",
    name: "Naan",
    aliases: ["plain naan", "flatbread"],
    servingGrams: 44,
    cuisineTags: ["desi"],
    commonAllergens: ["wheat", "milk"],
    sourceId: 2707613,
    per100g: {
      caloriesKcal: 311,
      proteinG: 11.1,
      carbsG: 50.2,
      fatG: 7.28,
      fiberG: 5.2,
    },
  },
  {
    id: "paratha",
    name: "Paratha",
    aliases: ["porota", "parantha", "flatbread"],
    servingGrams: 70,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["wheat", "milk"],
    sourceId: 2707715,
    per100g: {
      caloriesKcal: 326,
      proteinG: 6.36,
      carbsG: 45.4,
      fatG: 13.2,
      fiberG: 9.6,
    },
  },
  {
    id: "puffed-rice",
    name: "Puffed rice",
    aliases: ["muri", "moodi", "murmura", "puffed rice cereal"],
    servingGrams: 30,
    cuisineTags: ["bengali", "desi"],
    sourceId: 171651,
    per100g: {
      caloriesKcal: 383,
      proteinG: 7.01,
      carbsG: 87.78,
      fatG: 0.9,
      fiberG: 1.4,
    },
  },
  {
    id: "potato-boiled",
    name: "Potato, boiled",
    aliases: ["alu", "aloo", "boiled potato", "aloo bhorta"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 2709388,
    per100g: {
      caloriesKcal: 93,
      proteinG: 1.95,
      carbsG: 21.5,
      fatG: 0.1,
      fiberG: 1.5,
    },
  },
  {
    id: "eggplant-cooked",
    name: "Eggplant, cooked",
    aliases: ["begun", "baingan", "aubergine", "begun bhorta"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169229,
    per100g: {
      caloriesKcal: 35,
      proteinG: 0.83,
      carbsG: 8.73,
      fatG: 0.23,
      fiberG: 2.5,
    },
  },
  {
    id: "okra-cooked",
    name: "Okra, cooked",
    aliases: ["dherosh", "bhindi", "okra bhaji"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169261,
    per100g: {
      caloriesKcal: 22,
      proteinG: 1.87,
      carbsG: 4.51,
      fatG: 0.21,
      fiberG: 2.5,
    },
  },
  {
    id: "bitter-gourd-cooked",
    name: "Bitter gourd, cooked",
    aliases: ["korola", "karela", "bitter melon"],
    servingGrams: 120,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168496,
    per100g: {
      caloriesKcal: 19,
      proteinG: 0.84,
      carbsG: 4.32,
      fatG: 0.18,
      fiberG: 2,
    },
  },
  {
    id: "green-beans-cooked",
    name: "Green beans, cooked",
    aliases: ["sheem-style beans", "beans bhaji", "snap beans"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169141,
    per100g: {
      caloriesKcal: 35,
      proteinG: 1.89,
      carbsG: 7.88,
      fatG: 0.28,
      fiberG: 3.2,
    },
  },
  {
    id: "cauliflower-cooked",
    name: "Cauliflower, cooked",
    aliases: ["fulkopi", "gobi", "cauliflower bhaji"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170397,
    per100g: {
      caloriesKcal: 23,
      proteinG: 1.84,
      carbsG: 4.11,
      fatG: 0.45,
      fiberG: 2.3,
    },
  },
  {
    id: "cabbage-cooked",
    name: "Cabbage, cooked",
    aliases: ["bandhakopi", "patta gobi", "cabbage bhaji"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169976,
    per100g: {
      caloriesKcal: 23,
      proteinG: 1.27,
      carbsG: 5.51,
      fatG: 0.06,
      fiberG: 1.9,
    },
  },
  {
    id: "bottle-gourd-cooked",
    name: "Bottle gourd, cooked",
    aliases: ["lau", "lauki", "dudhi", "calabash"],
    servingGrams: 180,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169233,
    per100g: {
      caloriesKcal: 15,
      proteinG: 0.6,
      carbsG: 3.69,
      fatG: 0.02,
      fiberG: 1.2,
    },
  },
  {
    id: "butternut-squash-cooked",
    name: "Butternut squash, cooked",
    aliases: ["winter squash", "kumra-style squash"],
    servingGrams: 180,
    cuisineTags: ["north-american-desi"],
    sourceId: 169296,
    per100g: {
      caloriesKcal: 40,
      proteinG: 0.9,
      carbsG: 10.49,
      fatG: 0.09,
      fiberG: 3.2,
    },
  },
  {
    id: "pumpkin-cooked",
    name: "Pumpkin, cooked",
    aliases: ["kumra", "kaddu", "pumpkin bhaji"],
    servingGrams: 180,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168449,
    per100g: {
      caloriesKcal: 20,
      proteinG: 0.72,
      carbsG: 4.9,
      fatG: 0.07,
      fiberG: 1.1,
    },
  },
  {
    id: "carrots-cooked",
    name: "Carrots, cooked",
    aliases: ["gajor", "gajar", "carrot sabzi"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170394,
    per100g: {
      caloriesKcal: 35,
      proteinG: 0.76,
      carbsG: 8.22,
      fatG: 0.18,
      fiberG: 3,
    },
  },
  {
    id: "green-peas-cooked",
    name: "Green peas, cooked",
    aliases: ["motor", "matar", "peas curry"],
    servingGrams: 120,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170420,
    per100g: {
      caloriesKcal: 84,
      proteinG: 5.36,
      carbsG: 15.63,
      fatG: 0.22,
      fiberG: 5.5,
    },
  },
  {
    id: "mustard-greens-cooked",
    name: "Mustard greens, cooked",
    aliases: ["shorshe shaak", "sarson ka saag", "mustard greens"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169257,
    per100g: {
      caloriesKcal: 26,
      proteinG: 2.56,
      carbsG: 4.51,
      fatG: 0.47,
      fiberG: 2,
    },
  },
  {
    id: "radish-raw",
    name: "Radish, raw",
    aliases: ["mula", "mooli", "radish salad"],
    servingGrams: 100,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169276,
    per100g: {
      caloriesKcal: 16,
      proteinG: 0.68,
      carbsG: 3.4,
      fatG: 0.1,
      fiberG: 1.6,
    },
  },
  {
    id: "turnip-cooked",
    name: "Turnip, cooked",
    aliases: ["shaljom", "shalgam", "turnip curry"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170058,
    per100g: {
      caloriesKcal: 22,
      proteinG: 0.71,
      carbsG: 5.06,
      fatG: 0.08,
      fiberG: 2,
    },
  },
  {
    id: "plantain-boiled",
    name: "Green plantain, boiled",
    aliases: ["kacha kola", "kancha kola", "raw banana curry"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168216,
    per100g: {
      caloriesKcal: 121,
      proteinG: 1.09,
      carbsG: 29.15,
      fatG: 0.08,
      fiberG: 2.6,
    },
  },
  {
    id: "cilantro-raw",
    name: "Cilantro, raw",
    aliases: ["dhonia pata", "dhania", "coriander leaves"],
    servingGrams: 10,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169997,
    per100g: {
      caloriesKcal: 23,
      proteinG: 2.13,
      carbsG: 3.67,
      fatG: 0.52,
      fiberG: 2.8,
    },
  },
  {
    id: "green-chili-raw",
    name: "Green chili, raw",
    aliases: ["kacha morich", "hari mirch", "green chile"],
    servingGrams: 5,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170497,
    per100g: {
      caloriesKcal: 40,
      proteinG: 2,
      carbsG: 9.46,
      fatG: 0.2,
      fiberG: 1.5,
    },
  },
  {
    id: "lime-juice",
    name: "Lime juice",
    aliases: ["lebur rosh", "nimbu", "lime"],
    servingGrams: 30,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168156,
    per100g: {
      caloriesKcal: 25,
      proteinG: 0.42,
      carbsG: 8.42,
      fatG: 0.07,
      fiberG: 0.4,
    },
  },
  {
    id: "mango-raw",
    name: "Mango, raw",
    aliases: ["aam", "mango fruit"],
    servingGrams: 165,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169910,
    per100g: {
      caloriesKcal: 60,
      proteinG: 0.82,
      carbsG: 14.98,
      fatG: 0.38,
      fiberG: 1.6,
    },
  },
  {
    id: "apple-raw",
    name: "Apple, raw",
    aliases: ["apel", "apple with skin"],
    servingGrams: 180,
    cuisineTags: ["north-american-desi"],
    sourceId: 171688,
    per100g: {
      caloriesKcal: 52,
      proteinG: 0.26,
      carbsG: 13.81,
      fatG: 0.17,
      fiberG: 2.4,
    },
  },
  {
    id: "orange-raw",
    name: "Orange, raw",
    aliases: ["komola", "santra", "orange fruit"],
    servingGrams: 140,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169918,
    per100g: {
      caloriesKcal: 46,
      proteinG: 0.7,
      carbsG: 11.54,
      fatG: 0.21,
      fiberG: 2.4,
    },
  },
  {
    id: "guava-raw",
    name: "Guava, raw",
    aliases: ["peyara", "amrood", "guava fruit"],
    servingGrams: 165,
    cuisineTags: ["bengali", "desi"],
    sourceId: 173044,
    per100g: {
      caloriesKcal: 68,
      proteinG: 2.55,
      carbsG: 14.32,
      fatG: 0.95,
      fiberG: 5.4,
    },
  },
  {
    id: "papaya-raw",
    name: "Papaya, raw",
    aliases: ["pepe", "papita", "papaya fruit"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 169926,
    per100g: {
      caloriesKcal: 43,
      proteinG: 0.47,
      carbsG: 10.82,
      fatG: 0.26,
      fiberG: 1.7,
    },
  },
  {
    id: "dates-medjool",
    name: "Medjool dates",
    aliases: ["khejur", "khajoor", "dates"],
    servingGrams: 48,
    cuisineTags: ["bengali", "desi"],
    sourceId: 168191,
    per100g: {
      caloriesKcal: 277,
      proteinG: 1.81,
      carbsG: 74.97,
      fatG: 0.15,
      fiberG: 6.7,
    },
  },
  {
    id: "jackfruit-raw",
    name: "Jackfruit, raw",
    aliases: ["kathal", "kanthal", "jackfruit"],
    servingGrams: 150,
    cuisineTags: ["bengali", "desi"],
    sourceId: 174687,
    per100g: {
      caloriesKcal: 95,
      proteinG: 1.72,
      carbsG: 23.25,
      fatG: 0.64,
      fiberG: 1.5,
    },
  },
  {
    id: "coconut-milk-canned",
    name: "Coconut milk, canned",
    aliases: ["narikel dudh", "coconut milk"],
    servingGrams: 60,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170173,
    per100g: {
      caloriesKcal: 197,
      proteinG: 2.02,
      carbsG: 2.81,
      fatG: 21.33,
      fiberG: 0,
    },
  },
  {
    id: "coconut-meat-raw",
    name: "Coconut meat, raw",
    aliases: ["narikel", "grated coconut"],
    servingGrams: 30,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170169,
    per100g: {
      caloriesKcal: 354,
      proteinG: 3.33,
      carbsG: 15.23,
      fatG: 33.49,
      fiberG: 9,
    },
  },
  {
    id: "peanuts-roasted",
    name: "Peanuts, dry-roasted",
    aliases: ["badam", "chinabadam", "moongphali"],
    servingGrams: 28,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["peanuts"],
    sourceId: 173806,
    per100g: {
      caloriesKcal: 587,
      proteinG: 24.35,
      carbsG: 21.26,
      fatG: 49.66,
      fiberG: 8.4,
    },
  },
  {
    id: "almonds-raw",
    name: "Almonds",
    aliases: ["kath badam", "badam", "almond"],
    servingGrams: 28,
    cuisineTags: ["desi"],
    commonAllergens: ["tree_nuts"],
    sourceId: 170567,
    per100g: {
      caloriesKcal: 579,
      proteinG: 21.15,
      carbsG: 21.55,
      fatG: 49.93,
      fiberG: 12.5,
    },
  },
  {
    id: "cashews-raw",
    name: "Cashews",
    aliases: ["kaju", "cashew nuts"],
    servingGrams: 28,
    cuisineTags: ["bengali", "desi"],
    commonAllergens: ["tree_nuts"],
    sourceId: 170162,
    per100g: {
      caloriesKcal: 553,
      proteinG: 18.22,
      carbsG: 30.19,
      fatG: 43.85,
      fiberG: 3.3,
    },
  },
  {
    id: "butter-salted",
    name: "Butter, salted",
    aliases: ["makhan", "butter", "ghee substitute"],
    servingGrams: 5,
    cuisineTags: ["desi"],
    commonAllergens: ["milk"],
    sourceId: 173410,
    per100g: {
      caloriesKcal: 717,
      proteinG: 0.85,
      carbsG: 0.06,
      fatG: 81.11,
      fiberG: 0,
    },
  },
  {
    id: "canola-oil",
    name: "Canola oil",
    aliases: ["neutral cooking oil", "vegetable oil"],
    servingGrams: 5,
    cuisineTags: ["north-american-desi"],
    sourceId: 172336,
    per100g: {
      caloriesKcal: 884,
      proteinG: 0,
      carbsG: 0,
      fatG: 100,
      fiberG: 0,
    },
  },
  {
    id: "coriander-seed-ground",
    name: "Coriander seed, ground",
    aliases: ["dhonia", "dhania powder", "ground coriander"],
    servingGrams: 2,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170922,
    per100g: {
      caloriesKcal: 298,
      proteinG: 12.37,
      carbsG: 54.99,
      fatG: 17.77,
      fiberG: 41.9,
    },
  },
  {
    id: "mustard-seed-ground",
    name: "Mustard seed, ground",
    aliases: ["shorshe", "sarson", "mustard paste"],
    servingGrams: 5,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170929,
    per100g: {
      caloriesKcal: 508,
      proteinG: 26.08,
      carbsG: 28.09,
      fatG: 36.24,
      fiberG: 12.2,
    },
  },
  {
    id: "chili-powder",
    name: "Chili powder",
    aliases: ["morich gura", "mirch powder", "red chili powder"],
    servingGrams: 1,
    cuisineTags: ["bengali", "desi"],
    sourceId: 171319,
    per100g: {
      caloriesKcal: 282,
      proteinG: 13.46,
      carbsG: 49.7,
      fatG: 14.28,
      fiberG: 34.8,
    },
  },
  {
    id: "black-pepper-ground",
    name: "Black pepper, ground",
    aliases: ["gol morich", "kali mirch", "black pepper"],
    servingGrams: 1,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170931,
    per100g: {
      caloriesKcal: 251,
      proteinG: 10.39,
      carbsG: 63.95,
      fatG: 3.26,
      fiberG: 25.3,
    },
  },
  {
    id: "cinnamon-ground",
    name: "Cinnamon, ground",
    aliases: ["daruchini", "dalchini", "cinnamon"],
    servingGrams: 1,
    cuisineTags: ["bengali", "desi"],
    sourceId: 171320,
    per100g: {
      caloriesKcal: 247,
      proteinG: 3.99,
      carbsG: 80.59,
      fatG: 1.24,
      fiberG: 53.1,
    },
  },
  {
    id: "cardamom-ground",
    name: "Cardamom, ground",
    aliases: ["elach", "elaichi", "cardamom"],
    servingGrams: 1,
    cuisineTags: ["bengali", "desi"],
    sourceId: 170919,
    per100g: {
      caloriesKcal: 311,
      proteinG: 10.76,
      carbsG: 68.47,
      fatG: 6.7,
      fiberG: 28,
    },
  },
  {
    id: "tomato-paste",
    name: "Tomato paste, no salt added",
    aliases: ["tomato concentrate", "quick curry base"],
    servingGrams: 30,
    cuisineTags: ["north-american-desi"],
    sourceId: 170459,
    per100g: {
      caloriesKcal: 82,
      proteinG: 4.32,
      carbsG: 18.91,
      fatG: 0.47,
      fiberG: 4.1,
    },
  },
  {
    id: "table-salt",
    name: "Table salt",
    aliases: ["lobon", "namak", "salt"],
    servingGrams: 1,
    cuisineTags: ["bengali", "desi"],
    sourceId: 173468,
    per100g: { caloriesKcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  },
];

export const CURATED_FOOD_CATALOG: readonly CuratedFoodItem[] = SEEDS.map(
  (seed) => ({
    id: seed.id,
    name: seed.name,
    aliases: seed.aliases ?? [],
    servingDescription: `${seed.servingGrams} g`,
    servingGrams: seed.servingGrams,
    cuisineTags: seed.cuisineTags ?? [],
    dietaryTags: dietaryTagsForFood(seed.id),
    commonAllergens: seed.commonAllergens ?? [],
    nutritionPerServing: nutritionForGrams(seed.per100g, seed.servingGrams),
    source: "USDA FoodData Central",
    sourceId: seed.sourceId,
  }),
);

export function getCuratedFood(id: string): CuratedFoodItem | undefined {
  return CURATED_FOOD_CATALOG.find((item) => item.id === id);
}

export function curatedFoodSupportsDiet(
  item: CuratedFoodItem,
  dietStyle:
    "no_preference" | "omnivore" | "vegetarian" | "vegan" | "pescatarian",
): boolean {
  if (dietStyle === "vegan") return item.dietaryTags.includes("vegan");
  if (dietStyle === "vegetarian") {
    return (
      item.dietaryTags.includes("vegetarian") ||
      item.dietaryTags.includes("vegan")
    );
  }
  if (dietStyle === "pescatarian") {
    return item.dietaryTags.length > 0;
  }
  return true;
}

export function filterCuratedFoods(
  catalog: readonly CuratedFoodItem[],
  query: string,
): CuratedFoodItem[] {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return [...catalog];
  const tokens = normalized.split(/\s+/u).filter(Boolean);
  return catalog.filter((item) => {
    const haystack = [item.name, ...item.aliases, ...item.cuisineTags]
      .join(" ")
      .toLocaleLowerCase();
    return tokens.every((token) => haystack.includes(token));
  });
}

export function searchCuratedFoods(query: string): CuratedFoodItem[] {
  return filterCuratedFoods(CURATED_FOOD_CATALOG, query);
}
