ALTER TABLE "account_deletion_requests" DROP CONSTRAINT "account_deletion_requests_lifecycle_check";--> statement-breakpoint
ALTER TABLE "account_deletion_requests" ADD COLUMN "subscription_deletion_status" text DEFAULT 'not_started' NOT NULL;--> statement-breakpoint
ALTER TABLE "account_deletion_requests" ADD COLUMN "lease_token" uuid;--> statement-breakpoint
ALTER TABLE "account_deletion_requests" ADD COLUMN "lease_expires_at" timestamp with time zone;--> statement-breakpoint
UPDATE "account_deletion_requests" SET "subscription_deletion_status" = 'confirmed' WHERE "status" = 'completed';--> statement-breakpoint
CREATE INDEX "account_deletion_requests_lease_index" ON "account_deletion_requests" USING btree ("status","lease_expires_at");--> statement-breakpoint
ALTER TABLE "account_deletion_requests" ADD CONSTRAINT "account_deletion_requests_lease_check" CHECK (("account_deletion_requests"."lease_token" IS NULL AND "account_deletion_requests"."lease_expires_at" IS NULL) OR ("account_deletion_requests"."status" = 'pending' AND "account_deletion_requests"."lease_token" IS NOT NULL AND "account_deletion_requests"."lease_expires_at" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "account_deletion_requests" ADD CONSTRAINT "account_deletion_requests_subscription_deletion_status_check" CHECK ("account_deletion_requests"."subscription_deletion_status" IN ('not_started', 'queued', 'confirmed'));--> statement-breakpoint
ALTER TABLE "account_deletion_requests" ADD CONSTRAINT "account_deletion_requests_lifecycle_check" CHECK (("account_deletion_requests"."status" = 'pending' AND "account_deletion_requests"."clerk_user_id" IS NOT NULL AND "account_deletion_requests"."completed_at" IS NULL) OR ("account_deletion_requests"."status" = 'completed' AND "account_deletion_requests"."clerk_user_id" IS NULL AND "account_deletion_requests"."completed_at" IS NOT NULL AND "account_deletion_requests"."last_error_code" IS NULL AND "account_deletion_requests"."subscription_deletion_status" = 'confirmed'));
